version: '3.8'

services:
  caddy:
    image: caddy:2.7
    container_name: caddy
    depends_on:
      - frontend-birbs
      - backend-birbs
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Caddy config file from your project root
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      # Named volumes (Docker manages these; no host folder)
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    networks:
      - birbs_network

networks:
  birbs_network:
    external: false

volumes:
  caddy_data:
  caddy_config:
